version: '3.9'

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        command: gunicorn Biblioteca.wsgi:application --bind 0.0.0.0:8000
        user: root
        volumes:
          - ./src:/app
          - ./static:/static
        depends_on:
            - mysql
        networks:
            - app-network
        environment:
            DB_HOST: $DB_HOST
            DB_USER: $DB_USER
            DB_PASSWORD: $DB_PASSWORD
            TRUSTED_DOMAINS: $TRUSTED_DOMAINS
    mysql:
        image: mysql:8
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: myRootpwd32
            MYSQL_DATABASE: biblioteca
        networks:
            - app-network
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./static:/static
        networks:
            - app-network
        depends_on:
            - app

networks:
    app-network:
        driver: bridge
